name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          cmake: true
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel
      - name: Run tests
        if: success() && hashFiles('build/CTestTestfile.cmake') != ''
        run: ctest --test-dir build --output-on-failure
